# Generated by Django 2.1.2 on 2019-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('course_code', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
